version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mem0-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mem0root123
      MYSQL_DATABASE: mem0
      MYSQL_USER: mem0
      MYSQL_PASSWORD: mem0pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
    networks:
      - mem0-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Elasticsearch 向量存储
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: mem0-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - mem0-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Kibana (可选，用于 ES 管理)
  kibana:
    image: kibana:8.11.0
    container_name: mem0-kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - mem0-network

  # Mem0 Java 应用
  mem0-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mem0-app
    restart: unless-stopped
    environment:
      # 数据库配置
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mem0?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=mem0
      - SPRING_DATASOURCE_PASSWORD=mem0pass123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      
      # MyBatis 配置
      - MYBATIS_MAPPER_LOCATIONS=classpath:mapper/*.xml
      - MYBATIS_TYPE_ALIASES_PACKAGE=com.mem0.core.entity
      
      # Elasticsearch 配置
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_INDEX_PREFIX=mem0
      
      # DashScope API 配置 (需要替换为实际的 API Key)
      - DASHSCOPE_API_KEY=your-dashscope-api-key-here
      
      # 应用配置
      - SERVER_PORT=8080
      - LOGGING_LEVEL_COM_MEM0=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_AI=INFO
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - mem0-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/test/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    driver: local
  es_data:
    driver: local

networks:
  mem0-network:
    driver: bridge 